version: '3.8'

services:
  postgres-db:
    image: postgres:18
    container_name: postgres-db
    environment:
      POSTGRES_USER: walletuser
      POSTGRES_PASSWORD: walletpass
      POSTGRES_DB: walletdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql  # Важное изменение для Postgres 18+

  walletapi-app:
    build: .
    container_name: walletapi-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/walletdb
      SPRING_DATASOURCE_USERNAME: walletuser
      SPRING_DATASOURCE_PASSWORD: walletpass

volumes:
  pgdata:
